language: node_js
node_js:
  - "8"
cache: npm
install:
  - npm install -g firebase-tools
  - npm i
script:
    - npm run build
after_success:
  - npm run deploy -- --token $FIREBASE_TOKEN
branches:
  only:
    - master
